const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({headless:true,channel:'chrome'});
  fs.mkdirSync('artifacts',{recursive:true});
  const results=[];
  for (const width of [1440,390]) {
    const page = await browser.newPage({viewport:{width,height:900}});
    const errors=[];
    page.on('pageerror',error=>errors.push(error.message));
    page.on('response',response=>{if(response.status()>=400)errors.push(response.url());});
    await page.goto('http://127.0.0.1:4173');
    await page.waitForTimeout(900);
    assert(await page.locator('.site-loader').isVisible());
    assert(await page.locator('main').evaluate(e=>e.inert));
    await page.screenshot({path:`artifacts/loader-${width}.png`});
    await page.waitForFunction(()=>performance.now()-window.yohakuIntro.startedAt>=3300);
    assert(await page.evaluate(()=>document.documentElement.classList.contains('intro-loading')));
    await page.waitForFunction(()=>document.documentElement.classList.contains('intro-complete'));
    const elapsed=await page.evaluate(()=>performance.now()-window.yohakuIntro.startedAt);
    assert(elapsed>=3990&&elapsed<4500);
    assert(!(await page.locator('main').evaluate(e=>e.inert)));
    assert.equal(await page.locator('h1 .text-line').count(),2);
    await page.waitForTimeout(2800);
    await page.screenshot({path:`artifacts/motion-hero-${width}.png`});
    assert(await page.evaluate(()=>document.fonts.check('28px Cinzel')));
    const hero=await page.locator('.hero-image').evaluate(e=>({animation:getComputedStyle(e).animationName,duration:getComputedStyle(e).animationDuration,transform:getComputedStyle(e).transform}));
    assert.equal(hero.animation,'hero-approach');
    const padding=await page.locator('.concept').evaluate(e=>getComputedStyle(e).paddingTop);
    assert.equal(padding,width===1440?'0px':'72px');
    await page.locator('.concept-photo').scrollIntoViewIfNeeded();
    const photo=await page.locator('.concept-photo').evaluate(e=>({transform:getComputedStyle(e).transform,duration:getComputedStyle(e).transitionDuration}));
    assert.equal(photo.transform,'none');assert.equal(photo.duration,'2.4s');
    await page.waitForTimeout(2900);
    await page.screenshot({path:`artifacts/motion-concept-${width}.png`});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    assert.deepEqual(errors,[]);
    results.push({width,loaderMs:Math.round(elapsed),hero,padding,photo});
    await page.close();
  }
  const reduced=await browser.newPage({reducedMotion:'reduce'});
  await reduced.goto('http://127.0.0.1:4173');
  await reduced.waitForFunction(()=>document.documentElement.classList.contains('intro-complete'));
  assert.equal(await reduced.locator('.hero-image').evaluate(e=>getComputedStyle(e).animationName),'none');
  const nojs=await browser.newPage({javaScriptEnabled:false});
  await nojs.goto('http://127.0.0.1:4173');
  assert(!(await nojs.locator('.site-loader').isVisible()));
  assert(await nojs.locator('h1').isVisible());
  console.log(JSON.stringify({results,reducedMotion:'passed',noJavaScript:'passed'},null,2));
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
