const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const theme = path.join(root, 'wp-content/themes/axis-structure');
const write = (name, content) => { const p=path.join(theme,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,content); };
const img = (name,alt,cls='',hero=false) => `<img class="${cls}" src="assets/images/${name}.webp" width="1536" height="1024" alt="${alt}" ${hero?'fetchpriority="high"':'loading="lazy"'}>`;
const label = (n,text) => `<p class="section-label"><span>${n}</span>${text}</p>`;
const link = (text,id) => `<a class="text-link" href="#${id}">${text}<span aria-hidden="true">⟶</span></a>`;
const wave = `<svg class="wave" viewBox="0 0 600 100" fill="none" aria-hidden="true"><path d="M0 50H90l6-3 7 6 7-8 5 11 6-16 4 20 5-12 6 4 7-14 5 23 5-35 5 42 6-25 4 9 6-6 5 4 6-26 5 45 5-71 5 83 6-39 5 12 5-4 5-44 5 70 5-83 5 110 5-69 5 30 5-23 5 26 5-40 5 25 5-9 5 12 5-19 5 24 5-14 5 5 6-2 6 8 6-14 6 13 6-8 8 5H600" stroke="currentColor"/></svg>`;
const frame = `<svg class="frame-overlay" viewBox="0 0 660 540" fill="none" aria-hidden="true"><g stroke="currentColor" stroke-width=".7"><path d="M80 150 350 45 590 150 310 270ZM80 150V410L310 510 590 390V150M310 270V510M80 280 310 390 590 270M350 45V305M165 117V450M255 81V485M430 80V460M510 115V425M80 410 350 305 590 390M165 117 410 228M255 81 500 189M80 210 310 330 590 210M80 345 310 450 590 335"/><path d="M55 145V425M40 155H100M40 408H100M300 525 605 398M70 125 345 20 615 137" stroke-dasharray="3 5"/></g><g fill="currentColor"><circle cx="80" cy="150" r="2"/><circle cx="350" cy="45" r="2"/><circle cx="590" cy="150" r="2"/><circle cx="310" cy="270" r="2"/><circle cx="310" cy="510" r="2"/></g></svg>`;
const header = `<a class="skip-link" href="#main">本文へ移動</a>
<header class="site-header"><a class="brand" href="#top" aria-label="AXIS STRUCTURE ホーム"><span>AXIS</span><small>STRUCTURE</small></a><nav class="desktop-nav" aria-label="メインナビゲーション"><a href="#technology">TECHNOLOGY</a><a href="#structure">STRUCTURE</a><a href="#data">DATA</a><a href="#projects">PROJECTS</a><a href="#about">ABOUT</a><a href="#journal">JOURNAL</a></nav><a class="header-contact" href="#contact">技術相談・お問い合わせ <span>⟶</span></a><button class="menu-toggle" aria-label="メニューを開く" aria-expanded="false" aria-controls="site-menu"><span></span><span></span></button><nav id="site-menu" class="site-menu" aria-label="全メニュー" hidden><a href="#technology">TECHNOLOGY / 耐震技術</a><a href="#structure">STRUCTURE / 構造解析</a><a href="#data">DATA / 性能データ</a><a href="#projects">PROJECTS / 実績</a><a href="#about">ABOUT / 私たちについて</a><a href="#journal">JOURNAL / 技術レポート</a><a href="#company">COMPANY / 会社情報</a><a href="#contact">CONTACT / 技術相談</a><button data-detail="recruit">RECRUIT / 採用について</button></nav></header>`;
const main = `<main id="main">
<section class="hero" id="top" aria-labelledby="hero-title">${img('hero','夕景の山並みを背景に、温かな灯りがともるコンクリート住宅と水盤','hero-image',true)}<div class="hero-shade"></div><div class="hero-grid" aria-hidden="true"></div>${frame}<div class="hero-content"><div class="hero-kicker"><span>01</span><p>SEISMIC<br>ENGINEERING<br>STRUCTURAL<br>DESIGN</p></div><h1 id="hero-title">揺れに、<br>技術で答える。</h1><p class="hero-description">見えないリスクに、確かな答えを。<br>AXISの耐震技術が、<br>もっと安心できる未来をつくる。</p></div><div class="hero-level"><p>EARTHQUAKE<br>RESISTANCE</p><small>LEVEL</small><strong>03</strong><i></i></div><a class="scroll-cue" href="#problem">SCROLL<span></span></a><div class="hero-coordinates" aria-hidden="true">35.6812° N<br>139.7671° E <span>SAFETY<br>TECHNOLOGY<br>PEOPLE<br>FUTURE</span></div></section>
<section class="problem light section" id="problem">${label('02','PROBLEM')}<div class="problem-grid"><div class="section-copy"><h2>地震は、<br>いつもの暮らしを<br>一瞬で変えてしまう。</h2><p>日本は、世界でも有数の地震大国。<br>だからこそ、私たちは「もしも」ではなく、<br>「いつか」に備えた建築をつくり続けています。</p><span class="short-rule"></span></div><figure class="city-photo">${img('city','密集する都市の建築と遠くまで続く街並み')}${wave}<figcaption>OBSERVATION / TOKYO</figcaption></figure><div class="risk-panel"><div class="radar" aria-hidden="true"><span>＋</span></div><p class="eyebrow">SEISMIC RISK</p><p>揺れを知る。<br>備えを、設計する。</p><dl><div><dt>地震への備え</dt><dd>解析 <span>×</span> 設計</dd></div><div><dt>めざすのは</dt><dd>暮らしの継続</dd></div></dl><small>JAPAN / SEISMIC COUNTRY</small></div></div></section>
<section class="technology dark section" id="technology">${label('03','TECHNOLOGY')}<div class="technology-grid"><div class="section-copy"><h2>揺れを、<br>構造で制御する。</h2><p>AXISは、構造設計・解析・施工のすべてをつなぎ、<br>地震エネルギーを受け流す耐震構造を追求します。</p>${link('耐震技術を読み解く','structure')}</div><figure class="technology-model">${img('structure','青い耐震部材を組み込んだ、柱と梁の構造模型')}<figcaption>FRAME 03 / SEISMIC CONTROL</figcaption></figure><ol class="principles"><li><span>01</span><div><h3>ENERGY CONTROL</h3><p>地震エネルギーの制御</p></div></li><li><span>02</span><div><h3>HIGH RIGIDITY</h3><p>高い構造剛性</p></div></li><li><span>03</span><div><h3>LONG LIFE</h3><p>長く使い続けられる構造</p></div></li></ol></div></section>
<section class="data light section" id="data">${label('04','DATA')}<div class="data-grid"><div class="section-copy"><h2>性能を、<br>数字で証明する。</h2><p>解析・実験・施工データに基づく、<br>地震への細やかなシミュレーション。</p><button class="text-link" data-detail="data">性能データについて<span>⟶</span></button></div><dl class="metrics"><div><dt>耐震等級</dt><dd>03</dd><small>SEISMIC GRADE</small></div><div><dt>最大変形量</dt><dd>-42<span>%</span></dd><small>従来工法比 / 想定値</small></div><div><dt>構造解析</dt><dd>1,240</dd><small>CASES</small></div><div><dt>累計施工</dt><dd>386</dd><small>BUILDINGS</small></div></dl></div><p class="data-note">※ ポートフォリオ用の架空データです。実際の性能・施工実績を示すものではありません。</p></section>
<section class="structure dark section" id="structure">${label('05','STRUCTURE')}<div class="structure-grid"><div class="section-copy"><h2>見えない構造まで、<br>設計する。</h2><p>3Dモデルによる構造解析で、<br>地震時の挙動をシミュレーション。<br>設計段階から、確かな安全性を追求します。</p><button class="text-link" data-detail="structure">構造解析について詳しく見る<span>⟶</span></button></div><figure class="analysis-model">${img('structure','柱・梁・耐震部材の関係を可視化した構造解析イメージ')}${frame}<figcaption>STRUCTURAL ANALYSIS / MODEL 03</figcaption></figure><div class="analysis-list"><div><div class="analysis-thumb heatmap">${frame}</div><p><strong>構造解析</strong><span>地震時の応力シミュレーション</span></p></div><div><div class="analysis-thumb joint" aria-hidden="true"><i></i><b>＋</b></div><p><strong>接合部詳細</strong><span>力を確実に伝える接合設計</span></p></div><div><div class="analysis-thumb waveform">${wave}</div><p><strong>地震応答シミュレーション</strong><span>応答波形による検証</span></p></div></div></div></section>
<section class="projects light section" id="projects">${label('06','PROJECTS')}<div class="section-heading"><h2>技術が支える、<br>その先の暮らし。</h2><p>暮らしの器から、都市の基盤まで。<br>構造の可能性を、一つずつかたちに。</p></div><div class="project-grid">${[['hero','RESIDENCE A','RC HOUSE / TOKYO','夕景のコンクリート住宅'],['office','OFFICE FRAME','STEEL STRUCTURE / OSAKA','大きな開口を持つ建築の内部'],['public','SEISMIC RENOVATION','PUBLIC FACILITY / KOBE','中庭と自然光を取り込む建築']].map((p,i)=>`<button class="project-card" data-detail="project-${i}"><div class="project-image">${img(p[0],p[3])}<span class="project-view">VIEW PROJECT ↗</span></div><div class="project-heading"><span>0${i+1}</span><h3>${p[1]}</h3><span>↗</span></div><p>${p[2]}</p></button>`).join('')}</div><p class="caption-note">CONCEPT PROJECTS — 掲載する建築・実績はすべて架空のイメージです。</p></section>
<section class="about light section" id="about">${label('07','ABOUT')}<div class="about-grid"><div><p class="eyebrow">PRECISION BUILDS TRUST.</p><h2>構造から、<br>未来をつくる。</h2></div><div><p class="about-intro">強さには、理由がある。<br>その理由を、私たちは設計する。</p><p>建物を支える、見えない構造。<br>私たちは研究・設計・施工をひとつにつなぎ、<br>技術とデータで、安心の根拠をつくります。</p><div class="about-pillars"><span><small>01 / RESEARCH</small>研究</span><span><small>02 / DESIGN</small>設計</span><span><small>03 / BUILD</small>施工</span></div></div></div><div class="about-word" aria-hidden="true">STRUCTURAL ENGINEERING</div></section>
<section class="journal light section" id="journal">${label('08','JOURNAL')}<div class="journal-grid"><div><h2>安全を、<br>ひもとく。</h2><p>構造と耐震の、その一歩先へ。<br>AXISの技術ノート。</p></div><div class="report-list">${[['021','2026.09.04','耐震','耐震等級から考える、住まいの安全。'],['020','2026.08.21','構造','見えない接合部が、建物の強さを決める。'],['019','2026.08.07','研究','シミュレーションで読み解く、地震の力。']].map((p,i)=>`<button data-detail="report-${i}" class="report"><span class="report-no">TECH REPORT ${p[0]}</span><span class="report-meta">${p[1]} <span>${p[2]}</span></span><h3>${p[3]}</h3><span class="report-arrow">↗</span></button>`).join('')}</div></div></section>
<section class="contact dark section" id="contact">${label('09','CONTACT')}<div class="contact-grid"><h2>BUILD<br>FOR THE<br><span>UNKNOWN.</span></h2><div><p class="contact-jp">未知の揺れに、<br>備える。</p><p>これからの建築について、<br>構造から、一緒に考えませんか。</p><button class="contact-button" data-detail="contact">技術相談する <span>↗</span></button><button class="text-link" data-detail="request">資料請求<span>⟶</span></button></div></div><div class="contact-cross" aria-hidden="true">＋</div></section>
</main>`;
const footer = `<footer class="site-footer dark" id="company"><div class="footer-top"><a class="brand" href="#top"><span>AXIS</span><small>STRUCTURE</small></a><p>構造を知る。未来を支える。<br><small>SEISMIC ENGINEERING / STRUCTURAL DESIGN</small></p><div><button data-detail="company">会社情報 ↗</button><button data-detail="recruit">採用情報 ↗</button><button data-detail="privacy">プライバシーについて ↗</button></div></div><div class="footer-bottom"><span>© AXIS STRUCTURE</span><span>FICTIONAL BRAND / PORTFOLIO CONCEPT</span><a href="#top">BACK TO TOP ↑</a></div></footer><dialog id="detail-dialog" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="閉じる">×</button><p class="eyebrow" id="dialog-label"></p><h2 id="dialog-title"></h2><div id="dialog-body"></div><p class="dialog-note">AXIS STRUCTUREはポートフォリオ用の架空ブランドです。</p></dialog>`;
write('template-parts/home.php',main.replaceAll('src="assets/', 'src="<?php echo esc_url(get_template_directory_uri()); ?>/assets/'));
write('header.php',`<!doctype html>\n<html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head><body <?php body_class(); ?>><?php wp_body_open(); ?>\n${header.replaceAll('href="#','href="<?php echo esc_url(home_url(\'/\')); ?>#')}`);
write('footer.php',`${footer.replaceAll('href="#','href="<?php echo esc_url(home_url(\'/\')); ?>#')}\n<?php wp_footer(); ?></body></html>`);
write('front-page.php',`<?php get_header(); get_template_part('template-parts/home'); get_footer(); ?>`);
const generic=`<?php get_header(); ?><main id="main" class="document-page light section"><p class="eyebrow">AXIS STRUCTURE</p><?php if (have_posts()) : while (have_posts()) : the_post(); ?><article><h1><?php the_title(); ?></h1><?php if (has_post_thumbnail()) { the_post_thumbnail('large'); } ?><div class="entry-content"><?php the_content(); ?></div></article><?php endwhile; else : ?><h1>記事はまだありません。</h1><?php endif; ?></main><?php get_footer(); ?>`;
write('index.php',generic);write('page.php',generic);write('single.php',generic);
write('archive.php',`<?php get_header(); ?><main id="main" class="document-page light section"><h1><?php the_archive_title(); ?></h1><?php if (have_posts()) : while(have_posts()) : the_post(); ?><article><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><?php the_excerpt(); ?></article><?php endwhile; the_posts_pagination(); else : ?><p>記事はまだありません。</p><?php endif; ?></main><?php get_footer(); ?>`);
const html=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="揺れに、技術で答える。架空の構造設計・耐震技術企業 AXIS STRUCTUREのポートフォリオサイト。"><meta name="theme-color" content="#101318"><title>AXIS STRUCTURE｜揺れに、技術で答える。</title><link rel="icon" href="assets/svg/favicon.svg" type="image/svg+xml"><link rel="preload" href="assets/images/hero.webp" as="image" fetchpriority="high"><link rel="stylesheet" href="assets/css/main.css"><link rel="stylesheet" href="assets/css/motion.css"><script src="assets/js/intro-boot.js"></script><script src="assets/js/main.js" defer></script><script src="assets/js/vendor/gsap.min.js" defer></script><script src="assets/js/vendor/ScrollTrigger.min.js" defer></script><script src="assets/js/animation-utils.js" defer></script><script src="assets/js/loader.js" defer></script><script src="assets/js/hero.js" defer></script><script src="assets/js/technology.js" defer></script><script src="assets/js/scroll.js" defer></script><script src="assets/js/cursor.js" defer></script><script src="assets/js/motion.js" defer></script></head><body>${header}${main}${footer}</body></html>`;
write('preview.html',html);fs.writeFileSync(path.join(root,'index.html'),html.replaceAll('"assets/','"wp-content/themes/axis-structure/assets/'));
console.log('Static preview and WordPress templates built.');
